### ISSUE TITLE
Unable to de-jsonize a class when a construct is marked @jsonize

### ISSUE THREAD

**Issue by SerialVelocity** [rcorre/jsonizer#20] opened 2015-03-28 15:53 UTC
Hey,

I get this error:

```
core.exception.AssertError@../../../../.dub/packages/jsonizer-0.3.0/src/jsonizer/fromjson.d(190): A must have a no-args constructor to support extract
```

when calling fromJSON on:

``` d
class A {
  int a;

  @jsonize
  public this(string a) {
    this.a = a.to!int;
  }
}
```

**Comment by SerialVelocity** [comment] 2015-03-28 15:55
Also, I think that `assert` should be a `static assert` so it is thrown at compile-time, not run-time

**Comment by SerialVelocity** [comment] 2015-03-29 01:35
Could you tag a new release with these changes? Thanks! :)

**Comment by SerialVelocity** [comment] 2015-03-29 01:43
Actually, this isn't entirely fixed. Could you fix this and then tag a new release?

New example:

``` d
class A {
  int a;

  @jsonize
  public this(string aStr) {
    this.a = aStr.to!int;
  }
}
```

The difference is that the constructor argument is named differently to the parameters. Using `@jsonize` with the constructor shouldn't even be looking at the fields. I would expect this constructor to work with:

``` json
{
  "aStr": "bob"
}
```

but **not** with

``` json
{
  "a": "bob"
}
```

Also, **not** with

``` json
{
  "a": 5
}
```

**Comment by rcorre** [comment] 2015-03-29 03:16
Forgot to push tag (fixed now), but that example should work as intended (with the exception that "bob" cannot be converted to an int).

**Comment by SerialVelocity** [comment] 2015-03-29 10:32
This is throwing runtime exceptions for me from asserts.

Could you change these lines in `fromjson.d` to static asserts (and possibly more): 145, 282.

I know 282 should be changed. Not so sure about 145, I just found it with find & replace.

**Comment by SerialVelocity** [comment] 2015-03-29 10:33
(and the example above is missing `mixin JsonizeMe`)

So, because of the asserts not being static, are you running fromJSON!A()? That is what causes it to fail.

**Comment by SerialVelocity** [comment] 2015-03-29 10:38
Oh! I see what the issue is. It should work if I don't include `mixin JsonizeMe`. That seems a bit weird btw.

**Comment by SerialVelocity** [comment] 2015-03-29 10:53
Sorry for all the comments, I think i've figured it out. This should fail with a `JsonizeMismatchException`:

```
import std.conv : to;
import std.json : parseJSON;
import jsonizer : fromJSON, jsonize;

private class A {
  private const int a;

  @jsonize
  public this(int a) {
    this.a = a;
  }
}

void main() {
  `{}`.parseJSON().fromJSON!A();
}
```

not, with a default constructor error. Not that it is now using the same type and variable names in the constructor to simplify the example.

# 

So, to summarise what I've found so far:
- It's odd that you exclude `mixin JsonizeMe` when using a default constructor.
- Lines 145 and 282 should probably be `static assert` so that edge cases like this don't occur (may require a small refactor like making `mixin JsonizeMe` insert a static method which creates the object).
- Not having a default constructor throws assertions at runtime on invalid data (shouldn't happen for this) about no default constructor instead of a `JsonizeMismatchException`.

Finally got to the bottom of this!

**Comment by rcorre** [comment] 2015-03-29 12:16
> It's odd that you exclude mixin JsonizeMe when using a default constructor.
> `JsonizeMe` is not necessary if you are only calling `fromJSON` and using a custom constructor, as your constructor does all the work that the generated `_fromJSON` method would have done.
> 
> Lines 145 and 282 should probably be static assert so that edge cases like this don't occur (may require a small refactor like making mixin JsonizeMe insert a static method which creates the object).

Line 145 is trivially fixed. Line 282 cannot be a static assert, but the error message can be fixed. The problem isn't that you don't have a default constructor, its that I tried all your custom constructors and could not get one to match.
I'm planning on adding a `JsonizeConstructorException` to provide detail on exactly what I tried while attempting to construct your object.

> Not having a default constructor throws assertions at runtime on invalid data (shouldn't happen for this) about no default constructor instead of a JsonizeMismatchException.

This is really the same as above - I need to throw a more detailed exception here.

Thanks for tracking this all down!

**Comment by SerialVelocity** [comment] 2015-03-29 15:53
Also, since that line was an assert, what happens when you compile in release mode? the assert won't exist. :)

**Closed as completed** 2015-03-29 22:07 UTC
